modLoader="javafml"
loaderVersion="[2,)"
license="Not specified"

[[mods]]
modId="speciment_mod"
version="0.0.6"
displayName="speciment mod"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="JOYKIX, Pakoro, D3monDark"
description="Un mod fait pour des specimen"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.speciment_mod]]
    modId="neoforge"
    type="required"
    versionRange="[20.6.117,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.speciment_mod]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.6]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.speciment_mod]]
    modId="geckolib"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration